---
- name: Gather facts about all servers
  hosts: all
  gather_facts: true # default value but we can be explicit
  tasks:
    - name: Show ansible_os_family
      ansible.builtin.debug:
        msg: "ansible_os_family is {{ ansible_os_family }}"
    - name: Show mount points
      ansible.builtin.debug:
        msg: "mount points are {{ ansible_mounts }}" # doesn't work on Windows
      when: ansible_os_family == "RedHat" # so we need to filter out Windows
